home/urls.py
from django.urls import path
from .views import universities, university, filter_uni

app_name = 'home'

urlpatterns = [
    path('', universities, name='universities'),
    path('<int:id>', university, name='university'),
    path('<str:keyword>', filter_uni, name='filter'),
]

scorize/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class University(models.Model):
    class Meta:
        verbose_name_plural = _('universities')

    PUBLIC = 'public university'
    PRIVATE = 'private university'
    ARTS = 'liberal arts college'
    COMMUNITY = 'community college'

    TYPE_CHOICES = [
        (PUBLIC, PUBLIC),
        (PRIVATE, PRIVATE),
        (ARTS, ARTS),
        (COMMUNITY, COMMUNITY),
    ]
    
    city = models.ForeignKey('City', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    acronym = models.CharField(max_length=15)
    logo_pic = models.ImageField(upload_to="logos")
    overview =  models.TextField()
    date_established = models.DateField()
    total_students = models.PositiveIntegerField()
    international_students = models.PositiveIntegerField()
    website = models.URLField()
    acceptance_rate = models.FloatField()

    uni_type = models.CharField(
        max_length=100,
        choices=TYPE_CHOICES,
    )

    def __str__(self) -> str:
        return f'{self.name}'

class City(models.Model):
    class Meta:
        verbose_name_plural = _('cities')

    name = models.CharField('city name', max_length=100,)
    country = models.ForeignKey('Country', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.name}'


class Country(models.Model):
    class Meta:
        verbose_name_plural = _('countries')

    name = models.CharField('country name', max_length=100)

    def __str__(self) -> str:
        return f'{self.name}'

home/views.py
from django.shortcuts import render
from .models import University, City, Country
from django.core.paginator import Paginator
from django.db.models import Q, F
from django.views.decorators.cache import cache_page
from django.core.cache import cache

# Create your views here.

def universities(request):
    if request.method == 'POST':        
        # this is when user is searching
        search_word = request.POST.get('search')
        
        universities = University.objects.all().filter(
            Q(name__contains=search_word)
            
            | Q(city__name__contains=search_word)
            
            | Q(city__country__name__contains=search_word)
        ).order_by('-date_established')
    else:
        universities = cache.get('universities')
        if universities is None:
            universities = University.objects.all().order_by('-date_established')
            cache.set('universities', universities, 60 * 15)  # Cache for 15 minutes
    
    cities = cache.get('cities')
    if cities is None:
        cities = City.objects.all()
        cache.set('cities', cities, 60 * 15) 
    
    countries = cache.get('countries')
    if countries is None:
        countries = Country.objects.all()
        cache.set('countries', countries, 60 * 15) 

    paginator = Paginator(universities, 4) # Show 4 universities per page
    page_number = request.GET.get('page')
    # create page_obj that has the uni objects
    page_obj = paginator.get_page(page_number)
    # to have a list of numbers to create paginator in front
    number_of_pages = page_obj.paginator.num_pages
    number_of_pages_list = [x for x in range(1, number_of_pages + 1)]
    
    context = {
        'page_obj': page_obj,
        'num_pages': number_of_pages_list,
        'countries': countries,
        'cities': cities
    }

    return render(request, 'home/universities.html', context)


def filter_uni(request, keyword):
    if keyword != 'None':
        universities = University.objects.all().filter(
            Q(city__name__contains=keyword)
                
            | Q(city__country__name__contains=keyword)
        ).order_by('-date_established')
    else:
        universities = cache.get('universities')
        if universities is None:
            universities = University.objects.all().order_by('-date_established')
            cache.set('universities', universities, 60 * 15) 

    cities = cache.get('cities')
    if cities is None:
        cities = City.objects.all()
        cache.set('cities', cities, 60 * 15) 
    
    countries = cache.get('countries')
    if countries is None:
        countries = Country.objects.all()
        cache.set('countries', countries, 60 * 15) 

    paginator = Paginator(universities, 4) # Show 4 universities per page
    page_number = request.GET.get('page')
    # create page_obj that has the uni objects
    page_obj = paginator.get_page(page_number)
    # to have a list of numbers to create paginator in front
    number_of_pages = page_obj.paginator.num_pages
    number_of_pages_list = [x for x in range(1, number_of_pages + 1)]
    
    context = {
        'page_obj': page_obj,
        'num_pages': number_of_pages_list,
        'countries': countries,
        'cities': cities,
        'keyword': keyword
    }

    return render(request, 'home/universities.html', context)


# single university view
@cache_page(60 * 15)  # Cache for 15 minutes
def university(request, id):
    university = University.objects.get(id=id)
    context = {
        'uni': university,
    }

    return render(request, 'home/university.html', context)

templates/home/universities.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block title %}لیست دانشگاه‌ها{% endblock title %}

{% block body %}
    <div class="container mt-3">
        
        <div class="card text-center bg-light">
            <div class="card-body fs-1">
            لیست دانشگاه‌ها
            </div>
        </div>

        {% comment %} search {% endcomment %}
        <div class="card text-right bg-light mt-3">
            <div class="card-body ">
                <form action="{% url 'home:universities' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" class="form-control" id="search" name="search" placeholder="جستجو">
                    </div>
                    <button type="submit" class="btn btn-primary">جستجو</button>
                </form>
            </div>
        </div>

        {% comment %} filter {% endcomment %}
        <div class="card text-right bg-light mt-3">
            <div class="card-body row">
                <h4 class="mb-3">فیلتر</h4>
                <div class="col-6 col-md-3">
                    <h5>کشورها</h5>
                    {% for country in countries %}
                        <a {% if country.name == keyword %}href="{% url 'home:filter' 'None' %}" class="btn btn-dark" {% else %} href="{% url 'home:filter' country.name %}" class="btn btn-outline-dark"{% endif %}>
                            {{country.name}}
                        </a>
                    {% endfor %}
                </div>
                
                <div class="col-6 col-md-3">
                    <h5>شهرها</h5>
                    {% for city in cities %}
                        <a {% if city.name == keyword %}href="{% url 'home:filter' 'None' %}" class="btn btn-dark mb-2" {% else %} href="{% url 'home:filter' city.name %}" class="btn btn-outline-dark mb-2"{% endif %}>
                            {{city.name}}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>


        <div class="row mt-3 mb-3">
            {% for uni in page_obj %}
                <div class="col-6 mb-3">
                    <div class="card mb-3 bg-light" style="max-width: 540px;">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <a href="{% url 'home:university' uni.id %}">
                                    <img src="{{uni.logo_pic.url}}" class="img-thumbnail rounded-start" alt="...">
                                </a>
                            </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <a href="{% url 'home:university' uni.id %}" class="text-decoration-none text-black">
                                    <h5 class="card-title">{{uni.name}} ({{uni.acronym}})</h5>
                                </a>
                                <p class="card-text">شهر: {{uni.city}}</p>
                                <p class="card-text">کشور: {{uni.city.country.name}}</p>
                                <p class="card-text">نوع: {{uni.uni_type}}</p>
                                <p class="card-text">تعداد دانشجو: {{uni.total_students}}</p>
                                <p class="card-text">تعداد دانشجوهای بین‌المللی: {{uni.international_students}}</p>
                                <p class="card-text">ریت پذیرش: {{uni.acceptance_rate}}</p>
                                <p class="card-text">سال تاسیس: {{uni.date_established.year}}</p>
                                <p class="card-text"><small class="text-muted">وبسایت: <a target="_blank" class="text-left" href="{{uni.website}}">{{uni.website}}</a></small></p>
                                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{uni.id}}" aria-expanded="false" aria-controls="collapse{{uni.id}}">
                                    توضیحات
                                </button>
                                <p class="collapse card-text mt-3" id="collapse{{uni.id}}">
                                    {{uni.overview}}
                                </p>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>

                {% empty %}
                <h1 class="text-center mt-3 mb-3">
                    دانشگاهی یافت نشد
                </h1>
            {% endfor %}
        </div>

        {% comment %} paginator {% endcomment %}
        <nav class="mb-5" dir="ltr">
            <ul class="pagination pagination-lg justify-content-center">
                {% comment %} prev button {% endcomment %}
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#!" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                {% comment %} all pages {% endcomment %}
                {% for number in num_pages %}
                {% if number == page_obj.number %}
                    <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{number}}">{{number}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{number}}">{{number}}</a></li>
                {% endif %}
                {% endfor %}

                {% comment %} next button {% endcomment %}
                {% if page_obj.has_next  %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#!" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>

    </div>


{% endblock body %}

templates/home/university.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block title %}{{uni.name}}{% endblock title %}

{% block body %}
    <div class="container mt-3">
        
        <div class="card text-center bg-light">
            <div class="card-body fs-1">
                {{uni.name}}
            </div>
        </div>

        <div class="row mt-3 mb-3">
            <div class="card mb-3 position-absolute top-10 start-50 translate-middle-x bg-light" style="max-width:500px">
                <img src="{{uni.logo_pic.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'home:university' uni.id %}" class="text-decoration-none text-black">
                        <h5 class="card-title">{{uni.name}} ({{uni.acronym}})</h5>
                    </a>
                    <p class="card-text">شهر: {{uni.city}}</p>
                    <p class="card-text">کشور: {{uni.city.country.name}}</p>
                    <p class="card-text">نوع: {{uni.uni_type}}</p>
                    <p class="card-text">تعداد دانشجو: {{uni.total_students}}</p>
                    <p class="card-text">تعداد دانشجوهای بین‌المللی: {{uni.international_students}}</p>
                    <p class="card-text">سال تاسیس: {{uni.date_established.year}}</p>
                    <p class="card-text">توضیحات: {{uni.overview}}</p>
                    <p class="card-text"><small class="text-muted">وبسایت: <a target="_blank" class="text-left" href="{{uni.website}}">{{uni.website}}</a></small></p>
                </div>
              </div>
        </div>
        
    </div>
    
    
{% endblock body %}
    
    
    
    {% for uni in universities %}
        <div class="col-6 mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <a href="">
                            <img src="{{uni.logo_pic.url}}" class="img-thumbnail rounded-start" alt="...">
                        </a>
                    </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <a href="" class="text-decoration-none text-black">
                            <h5 class="card-title">{{uni.name}} ({{uni.acronym}})</h5>
                        </a>
                        <p class="card-text">شهر: {{uni.city}}</p>
                        <p class="card-text">کشور: {{uni.city.country.name}}</p>
                        <p class="card-text">نوع: {{uni.uni_type}}</p>
                        <p class="card-text">تعداد دانشجو: {{uni.total_students}}</p>
                        <p class="card-text">تعداد دانشجوهای بین‌المللی: {{uni.international_students}}</p>
                        <p class="card-text">سال تاسیس: {{uni.date_established.year}}</p>
                        <p class="card-text"><small class="text-muted">وبسایت: <a target="_blank" class="text-left" href="{{uni.website}}">{{uni.website}}</a></small></p>
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{uni.id}}" aria-expanded="false" aria-controls="collapse{{uni.id}}">
                            توضیحات
                        </button>
                        <p class="collapse card-text mt-3" id="collapse{{uni.id}}">
                            {{uni.overview}}
                        </p>
                    </div>
                </div>
                </div>
            </div>
        </div>
    {% endfor %}

templates/layout/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block body %}
    {% endblock body %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>